repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: local
    hooks:
    -   id: docker-tests
        name: Run Project Vox Tests (Docker)
        entry: ./scripts/run_tests.sh
        language: script
        pass_filenames: false
        always_run: true
