# Generated by Django 6.0.5 on 2026-05-19 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_campaign_campaigncandidate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='max_retries',
        ),
        migrations.RemoveField(
            model_name='campaigncandidate',
            name='retry_count',
        ),
    ]
