from __future__ import annotations

from dataclasses import dataclass, field
from typing import Optional


# ---------------------------------------------------------------------------
# Pre-call: produced by RecruiterAgent
# ---------------------------------------------------------------------------

@dataclass
class InterviewContext:
    """Structured JD intelligence passed from RecruiterAgent to OrchestratorAgent."""

    # JD-derived fields
    job_title: str = "Software Engineer"
    company_name: str = ""
    required_skills: list[str] = field(default_factory=list)
    nice_to_have_skills: list[str] = field(default_factory=list)
    experience_level: str = "mid"          # junior / mid / senior / lead / principal
    domain: str = ""                       # fintech, edtech, SaaS, infra, general …

    # Extended recruiter context (from structured UI or JD parsing)
    company_overview: str = ""             # company background / description
    team_details: str = ""                 # team size, structure, reporting line
    company_location: str = ""            # city / country / remote
    years_of_experience: str = ""         # e.g. "3-5 years", "5+"
    ctc_range: str = ""                   # offered salary, e.g. "15-20 LPA"
    required_joining_timeline: str = ""   # e.g. "Immediate", "Within 1 month"
    work_location_type: str = ""          # Hybrid / Onsite / WFH

    # Strategy fields (generated by RecruiterAgent)
    custom_questions: list[str] = field(default_factory=list)   # max 3 JD-specific probes
    phase_weights: dict = field(default_factory=dict)            # e.g. {"exploration": 1.5}

    # Async-enriched (filled by background intel fetch after call starts)
    company_context: dict = field(default_factory=dict)

    # Recruiter-supplied (legacy field, kept for compatibility)
    salary_range: Optional[str] = None

    # Original text — preserved for audit and LLM fallback
    raw_jd: str = ""

    # Health tracking
    recruiter_status: str = "pending"      # pending / completed / fallback_used

    def to_dict(self) -> dict:
        return {
            "job_title": self.job_title,
            "company_name": self.company_name,
            "required_skills": self.required_skills,
            "nice_to_have_skills": self.nice_to_have_skills,
            "experience_level": self.experience_level,
            "domain": self.domain,
            "company_overview": self.company_overview,
            "team_details": self.team_details,
            "company_location": self.company_location,
            "years_of_experience": self.years_of_experience,
            "ctc_range": self.ctc_range,
            "required_joining_timeline": self.required_joining_timeline,
            "work_location_type": self.work_location_type,
            "custom_questions": self.custom_questions,
            "phase_weights": self.phase_weights,
            "company_context": self.company_context,
            "salary_range": self.salary_range,
            "raw_jd": self.raw_jd[:500] if self.raw_jd else "",   # truncate for storage
            "recruiter_status": self.recruiter_status,
        }


# ---------------------------------------------------------------------------
# Post-call: produced by SummaryAgent
# ---------------------------------------------------------------------------

@dataclass
class CandidateSummary:
    """Compatibility evaluation produced by SummaryAgent after the call ends."""

    # Top-level verdict
    compatibility_level: str = "yellow"    # green / yellow / red
    compatibility_reason: str = ""         # one sentence explaining WHY

    # Recruiter-facing summary
    summary_bullets: list[str] = field(default_factory=list)   # 3-5 quick bullets
    match_points: list[str] = field(default_factory=list)       # what fits the role
    gap_points: list[str] = field(default_factory=list)         # what's missing / concerning

    # Specific gaps
    missing_skills: list[str] = field(default_factory=list)
    red_flags: list[str] = field(default_factory=list)

    # Action
    recommendation: str = ""               # shortlist / hold / reject
    recommendation_reason: str = ""

    # Health
    summary_status: str = "pending"        # pending / completed / fallback_used

    def to_dict(self) -> dict:
        return {
            "compatibility_level": self.compatibility_level,
            "compatibility_reason": self.compatibility_reason,
            "summary_bullets": self.summary_bullets,
            "match_points": self.match_points,
            "gap_points": self.gap_points,
            "missing_skills": self.missing_skills,
            "red_flags": self.red_flags,
            "recommendation": self.recommendation,
            "recommendation_reason": self.recommendation_reason,
            "summary_status": self.summary_status,
        }


# ---------------------------------------------------------------------------
# Post-call: produced by EvaluationAgent
# ---------------------------------------------------------------------------

@dataclass
class EvalDimension:
    """Score for a single evaluation dimension."""
    score: int = 5              # 1-10
    confidence: float = 0.5    # 0.0 = no data, 1.0 = very confident
    evidence: list[str] = field(default_factory=list)   # direct quotes / signals

    def to_dict(self) -> dict:
        return {
            "score": self.score,
            "confidence": self.confidence,
            "evidence": self.evidence,
        }


@dataclass
class EvalReport:
    """Structured evaluation produced by EvaluationAgent after the call ends."""

    # Top-level decision
    intent_score: int = 5
    call_outcome: str = "CONFUSED"          # INTERESTED|BUSY|NOT_INTERESTED|CALLBACK_REQUESTED|CONFUSED

    # Dimension scores (None = not enough data to score)
    technical_fit: Optional[EvalDimension] = None
    communication: Optional[EvalDimension] = None
    motivation_fit: Optional[EvalDimension] = None
    logistics_fit: Optional[EvalDimension] = None

    overall_confidence: float = 0.5         # aggregate confidence across dimensions

    # Summary
    summary_bullets: list[str] = field(default_factory=list)
    skills_verified: list[str] = field(default_factory=list)

    # Logistics (extracted from transcript)
    salary_expectation_lpa: Optional[float] = None
    current_ctc_lpa: Optional[float] = None
    notice_period_days: Optional[int] = None
    joining_timeline: Optional[str] = None
    other_offers: Optional[bool] = None

    # HR signals
    hr_flags: list[str] = field(default_factory=list)
    vibe_check: str = ""
    recommended_next_step: str = ""
    reasoning: str = ""                     # why this score + outcome

    # Internal
    raw_data: dict = field(default_factory=dict)
    evaluator_status: str = "pending"       # pending / completed / fallback_used

    def to_dict(self) -> dict:
        return {
            "intent_score": self.intent_score,
            "call_outcome": self.call_outcome,
            "technical_fit": self.technical_fit.to_dict() if self.technical_fit else None,
            "communication": self.communication.to_dict() if self.communication else None,
            "motivation_fit": self.motivation_fit.to_dict() if self.motivation_fit else None,
            "logistics_fit": self.logistics_fit.to_dict() if self.logistics_fit else None,
            "overall_confidence": self.overall_confidence,
            "summary_bullets": self.summary_bullets,
            "skills_verified": self.skills_verified,
            "salary_expectation_lpa": self.salary_expectation_lpa,
            "current_ctc_lpa": self.current_ctc_lpa,
            "notice_period_days": self.notice_period_days,
            "joining_timeline": self.joining_timeline,
            "other_offers": self.other_offers,
            "hr_flags": self.hr_flags,
            "vibe_check": self.vibe_check,
            "recommended_next_step": self.recommended_next_step,
            "reasoning": self.reasoning,
            "evaluator_status": self.evaluator_status,
            **{k: v for k, v in self.raw_data.items()
               if k not in ("intent_score", "call_outcome")},
        }
